# Generated by Django 2.2.9 on 2022-12-10 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_auto_20221210_0949"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-pub_date"]},
        ),
    ]
