# Generated by Django 4.1.4 on 2022-12-26 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_auto_20221210_1129"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-pub_date",)},
        ),
    ]
