# Generated by Django 2.2 on 2023-02-10 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20230207_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(
                help_text='Post to which comment is related to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='posts.Post',
                verbose_name='Post',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text='Moment in time when post was created',
                verbose_name='Publication date',
            ),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        help_text='Author who is followed by follower',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='following',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Author',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='Follower who going to subscribe to author',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='follower',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Follower',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Follower',
                'verbose_name_plural': 'Followers',
                'ordering': ('user',),
            },
        ),
    ]
